name: AWS Lambda Layer Deployment

on:
  push:
    tags:
      - t*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - uses: aws-actions/setup-sam@v1
      - run: make aws
#      - run: make aws-deploy


