name: AWS Lambda Layer Deployment

on:
  push:
    tags:
      - t*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MVN_OPTIONS: "--batch-mode --no-transfer-progress -Dgpg.skip"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: make aws
#        env:
#          SAM_BUILD_OPTIONS: --use-container
      - run: make aws-deploy


